name: 'Flutter Engine Action'
description: 'Setup environment and build Flutter Engine'
author: 'eggfly'
branding:
  icon: 'maximize'
  color: 'blue'
inputs:
  flutter-engine-revision:
    description: 'The revision of flutter engine git repo.'
    required: false
runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/build.sh
      shell: bash
