# This is a basic workflow to help you get started with Actions

name: Flutter Windows Host Engine

# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 14 * * *' # 22:00
    - cron:  '0 0 * * *'  # 8:00
    - cron:  '0 3 * * *'  # 11:00
    - cron:  '0 6 * * *'  # 14:00
    - cron:  '0 10 * * *' # 18:00
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  build-host-engine:
    runs-on: windows-latest
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          gn_params: --no-goma --no-lto --unopt
          ninja_path: ../out/host_debug_unopt
          flutter_engine_revision: main
      - uses: actions/upload-artifact@v3
        with:
          name: flutter_engine_windows_x64
          path: C:\\Users\\runneradmin\\flutter_engine\\src\\out
      - name: Run Goodbye!
        shell: bash
        run: echo Goodbye!

  build-x86-engine:
    runs-on: windows-latest
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./
        with:
          gn_params: --no-goma --no-prebuilt-dart-sdk --windows --windows-cpu x86
          ninja_path: ../out/win_debug_x86
          flutter_engine_revision: main
      - uses: actions/upload-artifact@v3
        with:
          name: flutter_engine_windows_x86
          path: C:\\Users\\runneradmin\\flutter_engine\\src\\out
      - name: Run Goodbye!
        shell: bash
        run: echo Goodbye!
